"""add handoff_triggered_at and claimed_at to conversations

Revision ID: ed701640feb1
Revises: f2fdf36e680f
Create Date: 2026-09-20 12:53:13.881774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed701640feb1'
down_revision: Union[str, None] = 'f2fdf36e680f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('handoff_triggered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('conversations', sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'claimed_at')
    op.drop_column('conversations', 'handoff_triggered_at')
    # ### end Alembic commands ###
