import uuid
from datetime import datetime, timezone

from sqlalchemy import DateTime, ForeignKey
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.core.db import Base


def _now() -> datetime:
    return datetime.now(timezone.utc)


class UUIDPKMixin:
    """Every table uses a UUID primary key rather than a sequential int,
    so ids are safe to expose externally and never collide across tenants
    generated by different services."""

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )


class TimestampMixin:
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_now, onupdate=_now, nullable=False
    )


class TenantMixin:
    """
    Every business table (everything except `tenants` itself) carries a
    tenant_id. This is the seam that keeps GRIP, Centro B, a restaurant,
    etc. fully isolated from each other on the same database, per the
    architecture doc's multi-tenant section. Row-level security (Postgres
    RLS) is layered on top of this column later — the column is what makes
    that possible; it is not optional even before RLS is turned on.
    """

    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("tenants.id", ondelete="RESTRICT"), nullable=False, index=True
    )
